# Generated by Django 5.0.2 on 2024-02-09 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0002_alter_hall_created_alter_hall_hall_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Schedule',
            fields=[
                ('course', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hall')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
