# Generated by Django 5.0.2 on 2024-02-09 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Schedule',
            fields=[
                ('start_time', models.PositiveIntegerField(blank=True, choices=[(7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 AM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM')], null=True)),
                ('end_time', models.PositiveIntegerField(blank=True, choices=[(7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 AM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM')], null=True)),
                ('course_information', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pre_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.pre_schedule')),
            ],
            options={
                'ordering': ['pre_schedule__date'],
                'unique_together': {('pre_schedule', 'start_time')},
            },
        ),
    ]
