# Generated by Django 4.2.6 on 2024-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_mainschedule_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainschedule',
            old_name='owner',
            new_name='rep_profile',
        ),
    ]
