# Generated by Django 4.2.6 on 2024-03-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_owner_mainschedule_rep_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainschedule',
            name='end_time',
            field=models.PositiveIntegerField(choices=[(7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM')]),
        ),
        migrations.AlterField(
            model_name='mainschedule',
            name='start_time',
            field=models.PositiveIntegerField(choices=[(7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM')]),
        ),
    ]
