# Generated by Django 5.0.2 on 2024-02-08 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
                ('hall_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
