# Generated by Django 5.0.2 on 2024-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_image',
            field=models.ImageField(blank=True, default='hall.png', null=True, upload_to='halls/'),
        ),
    ]
