# Generated by Django 4.2.6 on 2024-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_hall_created_alter_hall_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_image',
            field=models.ImageField(blank=True, default='default hall.png', null=True, upload_to='halls/'),
        ),
    ]
