# Generated by Django 4.2.6 on 2024-03-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_hall_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_image',
            field=models.ImageField(blank=True, default='dz2xsylz9dzakdpupstd', null=True, upload_to='halls/'),
        ),
    ]
