# Generated by Django 5.0.2 on 2024-03-02 01:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0005_alter_hall_hall_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, default="dz2xsylz9dzakdpupstd", max_length=255, null=True
            ),
        ),
    ]
