# Generated by Django 5.0.2 on 2024-03-02 01:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0007_alter_hall_hall_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dtbf1jnph/image/upload/v1709344440/halls/z72wqp7xmshse2nrxbzk.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
