# Generated by Django 4.2.6 on 2024-06-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_alter_hall_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
