# Generated by Django 4.2.6 on 2024-02-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('level', models.CharField(blank=True, choices=[(0, '0L'), (100, '100L'), (200, '200L'), (300, '300L'), (400, '400L'), (500, '500L'), (600, '600L'), (700, '700L')], max_length=3, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contatct_info', models.CharField(blank=True, max_length=11, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
