# Generated by Django 4.2.6 on 2024-02-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_repprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repprofile',
            name='level',
            field=models.PositiveIntegerField(blank=True, choices=[(100, '100L'), (200, '200L'), (300, '300L'), (400, '400L'), (500, '500L'), (600, '600L'), (700, '700L')], null=True),
        ),
        migrations.AlterField(
            model_name='repprofile',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
