# Generated by Django 4.2.6 on 2024-02-23 08:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_repprofile_level_alter_repprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repprofile',
            name='contact_info',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
