# Generated by Django 4.2.6 on 2024-03-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_defaultreplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultreplist',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.repprofile'),
        ),
    ]
