# Generated by Django 4.2.6 on 2024-03-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_defaultreplist_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultRepList',
        ),
    ]
